addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
//addSbtPlugin("com.github.sbt" % "sbt-ci-release"      % "1.0.0")
//addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "2.0.1")
//addSbtPlugin("org.scalameta"      % "sbt-native-image"              % "0.6.0")
addSbtPlugin("org.scalameta"      % "sbt-native-image"              % "0.3.4")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.5.0-RC2")
